---
title: "About"
toc: true
---

I am an innovation fellow at Northumbria University, working between the DCitizens and Centre for Digital Citizens projects. My research explores vulnerable groups' understanding of misinformation, disinformation, fake news and generative AI. This is with an aim to build their skills in recognising misleading/misinforming/ai-generated content.

My PhD research explored misinformation spread and correction within close-tie networks, investigating how technology could support misinformation correction when it is shared within groups of close ties (such as friend or family networks). 

## Experience
{{< fa briefcase >}} Innovation Fellow - Northumbria University (Newcastle upon Tyne, UK \| 2024 - Current)

{{< fa chalkboard-teacher >}} Associate Lecturer - Computer Science - Northumbria University (Newcastle upon Tyne, UK \| 2022 - 2024)

{{< fa briefcase >}} Senior Research Assistant - Northumbria University (Newcastle upon Tyne, UK \| 2023 - 2024)

{{< fa chalkboard-teacher >}} Demonstrator - Northumbria University (Newcastle upon Tyne, UK \| 2021 - 2023)

## Education

{{< fa graduation-cap >}} PhD in Computer Science - Northumbria University (Newcastle upon Tyne, UK - 2021-2024)

{{< fa graduation-cap >}} PGCE Computer Science with QTS - Newcastle Unniversity (Newcastle upon Tyne, UK - 2021-2022)

{{< fa graduation-cap >}} MSc in Advanced Computer Science - Northumbria University (Newcastle upon Tyne, UK - 2020)

{{< fa graduation-cap >}} BSc in Computer Science - Northumbria University (Newcastle upon Tyne, UK - 2019)

## Talks and Presentations
{{< fa university >}} Lab Talks |
{{< fa paper-plane >}} Public/Visiting talks |
{{< fa chalkboard-teacher >}} Conference Presentations

{{< fa paper-plane >}} Misinformation: Spread, Susceptibility and Correction
Guest Lecture - University College London

{{< fa chalkboard-teacher >}} From Banned to Influencer? Exploring XL Bully Discourse on Social Media 
Dec'24 - More than Human Digital Civics workshop - co-located with ACI2024

{{< fa university >}} Misinformation, communication, and challenges: how technology can be used to support misinformation correction within UK family networks?
Mar'24 NorSC Seminar Series

{{< fa chalkboard-teacher >}} Evaluating the Effects of Culture and Relationship Strength on Misinformation Challenging Behaviours Within the UK
Aug'23 - INTERACT 2023 

{{< fa chalkboard-teacher >}} "I figured her feeling a little bit bad was worth it to not spread that kind of hate": Exploring How UK Families Discuss and Challenge Misinformation.
Apr'23 - CHI 2023. 

{{< fa university >}} Handling misinformed family members: what do individuals do when their family are misinformed?
CHIRP Research Talk Series

{{< fa paper-plane >}} Studying the Impact of Gamification on Motivation in Remote Programming Education.
Sept'22 - Pint of Science Newcastle

{{< fa university >}} The role that mis/disinformation has in family relationships and conflicts in the household.
Jul'22 - NorSC Seminar Series

{{< fa chalkboard-teacher >}} Studying the Impact of Gamification on Motivation in Remote Programming Education. 
Oct'21 - European Conference on e-Learning 2021. 
