---
title: "Publications"
toc: true
---

{{< fa scroll >}}: Conference Paper | 
{{< fa newspaper >}}: Journal Article | 
{{< fa toolbox >}}:Workshop Paper |
{{< fa trophy >}}: Award Winning |
{{< fa people-group >}} Workshop Proposal |
{{< fa users-gear >}} Demo/Interactivity


## 2025

{{< fa scroll >}} [Accepted/in Press] **Scott. L.**, Warner, M., Coventry, L., E. Cecchinato, M. 2025. July. Accidental spreaders: How different roles interact during misinformation discussions. In Proceedings of 22nd European Conference on Computer-Supported Cooperative Work. European Society for Embedded Technologies (EUSSET)

{{< fa users-gear >}} Carter, A.R.L., Al-Shahrabi, D., Imoukhuede, W.A.P., **Scott, L.**, Jackson, D., Talhouk, R., Piedade, P., Montague, K., 2025. KaraokAI: Exploring the Potential of AI-Generated Karaoke for Academic Conferences and Research Experiences, in: Proceedings of the Extended Abstracts of the CHI Conference on Human Factors in Computing Systems, CHI EA ’25. Association for Computing Machinery, New York, NY, USA. https://doi.org/10.1145/3706599.3721113

## 2024 
{{< fa people-group >}} Gowland, S., **Scott, L.**, Handley, G., Carter, A., van der Linden, D. and Lawson, S., 2024, December. More than Human Digital Civics. In Proceedings of the International Conference on Animal-Computer Interaction (pp. 1-5).

## 2023

{{< fa scroll >}} **Scott, L.**, E. Cecchinato, M., Coventry, L., Warner, M. (2023). [Evaluating the Effects of Culture and Relationship Strength on Misinformation Challenging Behaviours Within the UK](https://doi.org/10.1007/978-3-031-42286-7_23). In: Abdelnour Nocera, J., Kristín Lárusdóttir, M., Petrie, H., Piccinno, A., Winckler, M. (eds) Human-Computer Interaction – INTERACT 2023. INTERACT 2023. Lecture Notes in Computer Science, vol 14144. Springer, Cham. 

{{< fa scroll >}} **Scott, L.**, Coventry, L., Cecchinato, M.E., Warner, M. (2023) ["I figured her feeling a little bit bad was worth it to not spread that kind of hate: Exploring How UK Families Discuss and Challenge Misinformation](https://dl.acm.org/doi/abs/10.1145/3544548.3581202). In Proceedings of the 2023 CHI Conference on Human Factors in Computing Systems (pp. 1-15). Association for Computing Machinery, Hamburg, Germany, 23/04/23.

## 2022


{{< fa toolbox >}} **Scott, L.**, Warner, M. Cecchinato, M.E. (2022) Addressing Misinformation within Family Networks. CSCW Workshop on Information-Seeking, [Finding Identity: Exploring the Role of Online Health Information in Illness Experience](https://sites.google.com/view/info-seeking101/home).  

## 2021
{{< fa scroll >}} {{< fa trophy >}} **Scott, L.** & Dalton, N. (2021) [Studying the Impact of Gamification on Motivation in Remote Programming Education](https://nrl.northumbria.ac.uk/id/eprint/47507/). In Proceedings of the 20th European Conference on e-Learning: ECEL 2021. Academic Conferences International Limited, Reading, Berlin, Germany, 28/10/21. [Certificate of Merit](https://www.academic-conferences.org/conferences/ecel/ecel-future-and-past/)